include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    one_member_abstracts: false # Used to check for existance of member functions
    prefer_expression_function_bodies: true
    prefer_typing_uninitialized_variables: true
    use_function_type_syntax_for_parameters: true
    unnecessary_getters: true