name: immortal
description: Trve immutable wrapper classes for the Dart collections List, Set and Map.
version: 2.0.0
homepage: https://github.com/strangeAeon/immortal

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  optional: ^3.0.2+1
  tuple: ^1.0.2

dev_dependencies:
  test: ^1.0.0
