name: immortal
description: Trve immutable wrapper classes for the Dart collections List, Set and Map.
version: 2.1.2-nullsafety
homepage: https://github.com/strangeAeon/immortal

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  optional: ^6.0.0-nullsafety.0
  tuple: ^2.0.0

dev_dependencies:
  effective_dart: ^1.3.1
  test: ^1.16.8
