name: immortal
description: Trve immutable wrapper classes for the Dart collections List, Set and Map.
version: 3.1.0
homepage: https://github.com/strangeAeon/immortal

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  optional: ^6.1.0
  tuple: ^2.0.0

dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.21.4
